package com.mycompany.trabajo;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Fechas extends javax.swing.JFrame {
    public static int variable;
    public static int variable2;
    /**
     * Creates new form Fechas
     */
    public Fechas() {
        initComponents();
        setLocationRelativeTo(null);
        llenarTabla();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        ButtonEliminar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonVerProductos = new javax.swing.JButton();
        ButtonVolver = new javax.swing.JButton();
        ButtonAgregar = new javax.swing.JButton();
        BotonDeportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonVerProductos.setText("Productos");
        ButtonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerProductosActionPerformed(evt);
            }
        });

        ButtonVolver.setText("Volver");
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });

        ButtonAgregar.setText("Agregar");
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        BotonDeportes.setText("Deportes");
        BotonDeportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonDeportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAgregar)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVolver)
                    .addComponent(ButtonVerProductos)
                    .addComponent(BotonDeportes))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        // TODO add your handling code here:
        int eliminarfecha = Tabla.getSelectedRow();
        
       
        Principal.ListaFecha.remove(eliminarfecha);
        
        llenarTabla();
       
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        // TODO add your handling code here:
        int actualizarfecha = Tabla.getSelectedRow();
        
        String cadena;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        cadena = JOptionPane.showInputDialog("Ingrese nueva fecha: dd/mm/aaaa");
            
            Date fecha = null;
            
            try {
                fecha = formato.parse(cadena);
            } 
            catch (ParseException ex) {
                System.out.println(ex);
            }
            
            Fecha f = new Fecha();
            f.setFecha(fecha);
            
            Principal.ListaFecha.set(actualizarfecha, f);
            JOptionPane.showMessageDialog(null, "Fecha actualizada con éxito.");
            llenarTabla();
        
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ButtonVolverActionPerformed

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        // TODO add your handling code here:
            String cadena;
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
            cadena = JOptionPane.showInputDialog("Ingrese nueva fecha: dd/mm/aaaa");
            
            Date fecha = null;
            
            try {
                fecha = formato.parse(cadena);
            } 
            catch (ParseException ex) {
                System.out.println(ex);
            }
            
            try{
                if((fecha.getYear()+1900<=2022)&&(fecha.getYear()+1900>=2021)){
                    Fecha f = new Fecha();
                    f.setFecha(fecha);
                    Principal.ListaFecha.add(f);
                    JOptionPane.showMessageDialog(null, "Fecha agregada con éxito.");
                }
                else
                    throw new FechaException("Formato de fecha inválido");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 0);
            }
            
            llenarTabla();
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    private void ButtonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerProductosActionPerformed
        // TODO add your handling code here:
         int indicefecha = Tabla.getSelectedRow();
         variable = indicefecha;
         Productos ventana = new Productos();
         ventana.setVisible(true);
         this.setVisible(false);
         
    }//GEN-LAST:event_ButtonVerProductosActionPerformed

    private void BotonDeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeportesActionPerformed
         int indicefecha = Tabla.getSelectedRow();
         variable2 = indicefecha;
         ClaveIntermediaEntreFechasYDeportes ventana = new ClaveIntermediaEntreFechasYDeportes();
         ventana.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BotonDeportesActionPerformed
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel(new String []{"Fechas"},Principal.ListaFecha.size());
        Tabla.setModel(modelo);
        
        TableModel modelofechas = Tabla.getModel();
        for(int i = 0 ; i < Principal.ListaFecha.size(); i++){
            Fecha fecha = Principal.ListaFecha.get(i);
            modelofechas.setValueAt(new SimpleDateFormat("dd/MM/yyyy").format(fecha.getFecha()), i, 0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDeportes;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonVerProductos;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
