package com.mycompany.trabajo;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonOpcion1 = new javax.swing.JRadioButton();
        RadioButtonOpcion2 = new javax.swing.JRadioButton();
        RadioButtonOpcion3 = new javax.swing.JRadioButton();
        RadioButtonOpcion4 = new javax.swing.JRadioButton();
        RadioButtonOpcion5 = new javax.swing.JRadioButton();
        RadioButtonOpcion6 = new javax.swing.JRadioButton();
        RadioButtonOpcion7 = new javax.swing.JRadioButton();
        RadioButtonOpcion8 = new javax.swing.JRadioButton();
        LabelOpcion = new javax.swing.JLabel();
        LabelMenu = new javax.swing.JLabel();
        ButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RadioButtonOpcion1.setText("Crear Fecha");
        RadioButtonOpcion1.setContentAreaFilled(false);
        RadioButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion1ActionPerformed(evt);
            }
        });

        RadioButtonOpcion2.setText("Imprimir Fecha");
        RadioButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion2ActionPerformed(evt);
            }
        });

        RadioButtonOpcion3.setText("Modificar Fecha");
        RadioButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion3ActionPerformed(evt);
            }
        });

        RadioButtonOpcion4.setText("Eliminar Fecha");
        RadioButtonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion4ActionPerformed(evt);
            }
        });

        RadioButtonOpcion5.setText("Crear Producto");
        RadioButtonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion5ActionPerformed(evt);
            }
        });

        RadioButtonOpcion6.setText("Imprimir Producto");
        RadioButtonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion6ActionPerformed(evt);
            }
        });

        RadioButtonOpcion7.setText("Modificar Producto");
        RadioButtonOpcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion7ActionPerformed(evt);
            }
        });

        RadioButtonOpcion8.setText("Eliminar Producto");
        RadioButtonOpcion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonOpcion8ActionPerformed(evt);
            }
        });

        LabelOpcion.setText("Elija una opción:");

        LabelMenu.setText("MENÚ");

        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(LabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RadioButtonOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonOpcion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RadioButtonOpcion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(ButtonAceptar)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMenu)
                .addGap(12, 12, 12)
                .addComponent(LabelOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ButtonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonOpcion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonOpcion5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonOpcion8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion1ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(true);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion1ActionPerformed

    private void RadioButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion2ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(true);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion2ActionPerformed

    private void RadioButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion3ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(true);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion3ActionPerformed

    private void RadioButtonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion4ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(true);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion4ActionPerformed

    private void RadioButtonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion5ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(true);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion5ActionPerformed

    private void RadioButtonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion6ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(true);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion6ActionPerformed

    private void RadioButtonOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion7ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(true);
        RadioButtonOpcion8.setSelected(false);
    }//GEN-LAST:event_RadioButtonOpcion7ActionPerformed

    private void RadioButtonOpcion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonOpcion8ActionPerformed
        // TODO add your handling code here:
        RadioButtonOpcion1.setSelected(false);
        RadioButtonOpcion2.setSelected(false);
        RadioButtonOpcion3.setSelected(false);
        RadioButtonOpcion4.setSelected(false);
        RadioButtonOpcion5.setSelected(false);
        RadioButtonOpcion6.setSelected(false);
        RadioButtonOpcion7.setSelected(false);
        RadioButtonOpcion8.setSelected(true);
    }//GEN-LAST:event_RadioButtonOpcion8ActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        // TODO add your handling code here:
        String cadena;
        
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        
        if(RadioButtonOpcion1.isSelected()){
            cadena = JOptionPane.showInputDialog("Ingrese nueva fecha: ");
            
            Date fecha = null;
            
            try {
                fecha = formato.parse(cadena);
            } 
            catch (ParseException ex) {
                System.out.println(ex);
            }
            
            Fecha f = new Fecha();
            f.setFecha(fecha);
            Principal.ListaFecha.add(f);
            
            
            JOptionPane.showMessageDialog(null, "Fecha agregada con éxito.");
        }
        
        if(RadioButtonOpcion2.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
        }
        
        if(RadioButtonOpcion3.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
         }
        if(RadioButtonOpcion6.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
        }    
    
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JLabel LabelMenu;
    private javax.swing.JLabel LabelOpcion;
    private javax.swing.JRadioButton RadioButtonOpcion1;
    private javax.swing.JRadioButton RadioButtonOpcion2;
    private javax.swing.JRadioButton RadioButtonOpcion3;
    private javax.swing.JRadioButton RadioButtonOpcion4;
    private javax.swing.JRadioButton RadioButtonOpcion5;
    private javax.swing.JRadioButton RadioButtonOpcion6;
    private javax.swing.JRadioButton RadioButtonOpcion7;
    private javax.swing.JRadioButton RadioButtonOpcion8;
    // End of variables declaration//GEN-END:variables
}