package com.mycompany.trabajo;


import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;

public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbOpcion1 = new javax.swing.JRadioButton();
        rdbOpcion2 = new javax.swing.JRadioButton();
        rdbOpcion3 = new javax.swing.JRadioButton();
        rdbOpcion4 = new javax.swing.JRadioButton();
        rdbOpcion5 = new javax.swing.JRadioButton();
        rdbOpcion6 = new javax.swing.JRadioButton();
        rdbOpcion7 = new javax.swing.JRadioButton();
        rdbOpcion8 = new javax.swing.JRadioButton();
        lblOpcion = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdbOpcion1.setText("Crear Fecha");
        rdbOpcion1.setContentAreaFilled(false);
        rdbOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion1ActionPerformed(evt);
            }
        });

        rdbOpcion2.setText("Imprimir Fecha");
        rdbOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion2ActionPerformed(evt);
            }
        });

        rdbOpcion3.setText("Modificar Fecha");
        rdbOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion3ActionPerformed(evt);
            }
        });

        rdbOpcion4.setText("Eliminar Fecha");
        rdbOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion4ActionPerformed(evt);
            }
        });

        rdbOpcion5.setText("Crear Producto");
        rdbOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion5ActionPerformed(evt);
            }
        });

        rdbOpcion6.setText("Imprimir Producto");
        rdbOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion6ActionPerformed(evt);
            }
        });

        rdbOpcion7.setText("Modificar Producto");
        rdbOpcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion7ActionPerformed(evt);
            }
        });

        rdbOpcion8.setText("Eliminar Producto");
        rdbOpcion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOpcion8ActionPerformed(evt);
            }
        });

        lblOpcion.setText("Elija una opción:");

        lblMenu.setText("MENÚ");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOpcion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOpcion5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbOpcion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(rdbOpcion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOpcion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(12, 12, 12)
                .addComponent(lblOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbOpcion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbOpcion5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbOpcion8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion1ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(true);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion1ActionPerformed

    private void rdbOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion2ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(true);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion2ActionPerformed

    private void rdbOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion3ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(true);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion3ActionPerformed

    private void rdbOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion4ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(true);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion4ActionPerformed

    private void rdbOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion5ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(true);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion5ActionPerformed

    private void rdbOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion6ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(true);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion6ActionPerformed

    private void rdbOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion7ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(true);
        rdbOpcion8.setSelected(false);
    }//GEN-LAST:event_rdbOpcion7ActionPerformed

    private void rdbOpcion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOpcion8ActionPerformed
        // TODO add your handling code here:
        rdbOpcion1.setSelected(false);
        rdbOpcion2.setSelected(false);
        rdbOpcion3.setSelected(false);
        rdbOpcion4.setSelected(false);
        rdbOpcion5.setSelected(false);
        rdbOpcion6.setSelected(false);
        rdbOpcion7.setSelected(false);
        rdbOpcion8.setSelected(true);
    }//GEN-LAST:event_rdbOpcion8ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String cadena;
        
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        
        if(rdbOpcion1.isSelected()){
            cadena = JOptionPane.showInputDialog("Ingrese nueva fecha: ");
            
            Date fecha = null;
            
            try {
                fecha = formato.parse(cadena);
            } 
            catch (ParseException ex) {
                System.out.println(ex);
            }
            
            Fecha f = new Fecha();
            f.setFecha(fecha);
            Principal.ListaFecha.add(f);
            
            
            JOptionPane.showMessageDialog(null, "Fecha agregada con éxito.");
        }
        
        if(rdbOpcion2.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
        }
        
        if(rdbOpcion3.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
         }
        if(rdbOpcion6.isSelected()){
            Fechas fechas = new Fechas () ;
            fechas.setVisible(true);
            this.setVisible(false);
        }    
    
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblOpcion;
    private javax.swing.JRadioButton rdbOpcion1;
    private javax.swing.JRadioButton rdbOpcion2;
    private javax.swing.JRadioButton rdbOpcion3;
    private javax.swing.JRadioButton rdbOpcion4;
    private javax.swing.JRadioButton rdbOpcion5;
    private javax.swing.JRadioButton rdbOpcion6;
    private javax.swing.JRadioButton rdbOpcion7;
    private javax.swing.JRadioButton rdbOpcion8;
    // End of variables declaration//GEN-END:variables
}